# Heissal Platform — unified developer entrypoints.
# Backend (Python) is driven by `uv` inside apps/api; frontend by pnpm/turbo.

.DEFAULT_GOAL := help
API_DIR := apps/api

.PHONY: help
help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}'

# --- Docker Compose ---
.PHONY: up down logs build ps
up: ## Start the full stack (db, redis, api, admin) in the background
	docker compose up -d --build
down: ## Stop the stack
	docker compose down
logs: ## Tail all service logs
	docker compose logs -f
build: ## Build all images
	docker compose build
ps: ## Show running services
	docker compose ps

# --- Backend (uv) ---
.PHONY: api-install api-dev migrate makemigration seed api-test api-lint api-typecheck
api-install: ## Install backend deps into a local venv
	cd $(API_DIR) && uv sync
api-dev: ## Run the API with autoreload (expects local postgres/redis)
	cd $(API_DIR) && uv run uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
migrate: ## Apply all Alembic migrations
	cd $(API_DIR) && uv run alembic upgrade head
makemigration: ## Create an autogenerated migration: make makemigration name="add x"
	cd $(API_DIR) && uv run alembic revision --autogenerate -m "$(name)"
seed: ## Seed permissions, roles, and the first superuser
	cd $(API_DIR) && uv run python -m app.db.seed
api-test: ## Run backend tests
	cd $(API_DIR) && uv run pytest -q
api-lint: ## Ruff lint
	cd $(API_DIR) && uv run ruff check .
api-typecheck: ## mypy type check
	cd $(API_DIR) && uv run mypy app

# --- Frontend (pnpm/turbo) ---
.PHONY: web-install web-dev web-lint web-typecheck web-build
web-install: ## Install all JS workspace deps
	pnpm install
web-dev: ## Run all frontend apps in dev
	pnpm dev
web-lint: ## Lint all JS packages
	pnpm lint
web-typecheck: ## Typecheck all JS packages
	pnpm typecheck
web-build: ## Build all JS packages
	pnpm build

# --- Aggregate ---
.PHONY: install lint test
install: api-install web-install ## Install everything
lint: api-lint web-lint ## Lint everything
test: api-test ## Run all tests
