"""stage3.1 quote options, supplier docs, media, transport tariffs

Revision ID: 03e1ff30d1ad
Revises: 0322f6c251ed
Create Date: 2026-08-24 20:24:10.795430
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '03e1ff30d1ad'
down_revision: Union[str, Sequence[str], None] = '0322f6c251ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('destination_images',
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_id', 'checksum', name='uq_destination_image_checksum')
    )
    op.create_index(op.f('ix_destination_images_checksum'), 'destination_images', ['checksum'], unique=False)
    op.create_index(op.f('ix_destination_images_destination_id'), 'destination_images', ['destination_id'], unique=False)
    op.create_table('destination_transport_modes',
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('travel_class', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('cost_basis', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('vat_inclusive', sa.Boolean(), nullable=False),
    sa.Column('vat_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_id', 'mode', 'travel_class', 'effective_from', name='uq_destination_transport_mode_period')
    )
    op.create_index(op.f('ix_destination_transport_modes_destination_id'), 'destination_transport_modes', ['destination_id'], unique=False)
    op.create_index(op.f('ix_destination_transport_modes_effective_from'), 'destination_transport_modes', ['effective_from'], unique=False)
    op.create_index(op.f('ix_destination_transport_modes_effective_to'), 'destination_transport_modes', ['effective_to'], unique=False)
    op.create_index(op.f('ix_destination_transport_modes_mode'), 'destination_transport_modes', ['mode'], unique=False)
    op.create_table('transfer_rates',
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=40), nullable=False),
    sa.Column('passenger_capacity', sa.Integer(), nullable=True),
    sa.Column('route_label', sa.String(length=200), nullable=False),
    sa.Column('price_per_leg', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('vat_inclusive', sa.Boolean(), nullable=False),
    sa.Column('vat_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_id', 'vehicle_type', 'route_label', 'effective_from', name='uq_transfer_rate_period')
    )
    op.create_index(op.f('ix_transfer_rates_destination_id'), 'transfer_rates', ['destination_id'], unique=False)
    op.create_index(op.f('ix_transfer_rates_effective_from'), 'transfer_rates', ['effective_from'], unique=False)
    op.create_index(op.f('ix_transfer_rates_effective_to'), 'transfer_rates', ['effective_to'], unique=False)
    op.create_index(op.f('ix_transfer_rates_vehicle_type'), 'transfer_rates', ['vehicle_type'], unique=False)
    op.create_table('activity_price_tiers',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('residence_category_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('vat_inclusive', sa.Boolean(), nullable=False),
    sa.Column('vat_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['residence_category_id'], ['residence_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'residence_category_id', 'label', 'effective_from', name='uq_activity_price_tier_period')
    )
    op.create_index(op.f('ix_activity_price_tiers_activity_id'), 'activity_price_tiers', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_price_tiers_effective_from'), 'activity_price_tiers', ['effective_from'], unique=False)
    op.create_index(op.f('ix_activity_price_tiers_effective_to'), 'activity_price_tiers', ['effective_to'], unique=False)
    op.create_table('property_images',
    sa.Column('accommodation_id', sa.UUID(), nullable=False),
    sa.Column('is_hero', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accommodation_id', 'checksum', name='uq_property_image_checksum')
    )
    op.create_index(op.f('ix_property_images_accommodation_id'), 'property_images', ['accommodation_id'], unique=False)
    op.create_index(op.f('ix_property_images_checksum'), 'property_images', ['checksum'], unique=False)
    op.create_table('supplier_documents',
    sa.Column('accommodation_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=300), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('extraction_error', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_documents_accommodation_id'), 'supplier_documents', ['accommodation_id'], unique=False)
    op.create_index(op.f('ix_supplier_documents_checksum'), 'supplier_documents', ['checksum'], unique=False)
    op.create_index(op.f('ix_supplier_documents_status'), 'supplier_documents', ['status'], unique=False)
    op.create_table('quote_options',
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('accommodation_id', sa.UUID(), nullable=False),
    sa.Column('room_type_id', sa.UUID(), nullable=True),
    sa.Column('meal_plan_id', sa.UUID(), nullable=True),
    sa.Column('rooms_required', sa.Integer(), nullable=True),
    sa.Column('meal_plan_fallback_from', sa.String(length=30), nullable=True),
    sa.Column('is_comparable', sa.Boolean(), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('agent_cover_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('chef_fee_per_meal', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('manual_meal_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id', 'accommodation_id', name='uq_quote_option_accommodation')
    )
    op.create_index(op.f('ix_quote_options_quote_id'), 'quote_options', ['quote_id'], unique=False)
    op.create_table('quote_rejected_candidates',
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('accommodation_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_rejected_candidates_quote_id'), 'quote_rejected_candidates', ['quote_id'], unique=False)
    op.create_table('quote_transport_segments',
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('travel_class', sa.String(length=20), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_id', sa.UUID(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=40), nullable=True),
    sa.Column('units', sa.Integer(), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('is_vvip', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_transport_segments_quote_id'), 'quote_transport_segments', ['quote_id'], unique=False)
    op.create_table('quote_version_options',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=True),
    sa.Column('accommodation_id', sa.UUID(), nullable=True),
    sa.Column('accommodation_name', sa.String(length=200), nullable=False),
    sa.Column('meal_plan_label', sa.String(length=60), nullable=True),
    sa.Column('rooms_required', sa.Integer(), nullable=True),
    sa.Column('cost_subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('contingency_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('profit_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('agent_cover_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('supplier_paid_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('retained_discount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('selling_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('per_person', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('is_comparable', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['option_id'], ['quote_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['version_id'], ['quote_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'option_id', name='uq_version_option')
    )
    op.create_index(op.f('ix_quote_version_options_version_id'), 'quote_version_options', ['version_id'], unique=False)
    op.create_table('supplier_document_extractions',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('proposed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('created_rate_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_rate_id'], ['accommodation_rates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['supplier_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_document_extractions_document_id'), 'supplier_document_extractions', ['document_id'], unique=False)
    op.create_index(op.f('ix_supplier_document_extractions_status'), 'supplier_document_extractions', ['status'], unique=False)
    op.add_column('accommodation_rates', sa.Column('vat_inclusive', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('accommodation_rates', sa.Column('vat_pct', sa.Numeric(precision=5, scale=2), server_default=sa.text('16'), nullable=False))
    op.add_column('accommodation_rates', sa.Column('rate_kind', sa.String(length=10), server_default='rack', nullable=False))
    op.add_column('accommodation_rates', sa.Column('supplier_discount_pct', sa.Numeric(precision=6, scale=3), nullable=True))
    op.add_column('accommodation_rates', sa.Column('source_document_id', sa.UUID(), nullable=True))
    op.add_column('accommodation_rates', sa.Column('child_min_age', sa.Integer(), nullable=True))
    op.add_column('accommodation_rates', sa.Column('child_max_age', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'accommodation_rates_source_document_id_fkey', 'accommodation_rates',
        'supplier_documents', ['source_document_id'], ['id'], ondelete='SET NULL',
    )
    op.add_column('accommodations', sa.Column('blurb', sa.Text(), nullable=True))
    op.add_column('activities', sa.Column('is_mandatory', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('activities', sa.Column('has_own_section', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('quotes', sa.Column('pax_count', sa.Integer(), nullable=True))
    op.add_column('quotes', sa.Column('profit_pct', sa.Numeric(precision=6, scale=3), nullable=True))
    op.add_column('quotes', sa.Column('contingency_pct', sa.Numeric(precision=6, scale=3), nullable=True))
    op.add_column('quotes', sa.Column('requested_meal_plan_id', sa.UUID(), nullable=True))
    op.add_column('quotes', sa.Column('valid_until', sa.Date(), nullable=True))
    op.add_column('quotes', sa.Column('selected_option_id', sa.UUID(), nullable=True))
    op.add_column('quotes', sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(
        'quotes_requested_meal_plan_id_fkey', 'quotes', 'meal_plans',
        ['requested_meal_plan_id'], ['id'], ondelete='RESTRICT',
    )
    op.create_foreign_key('fk_quotes_selected_option_id', 'quotes', 'quote_options', ['selected_option_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_quotes_selected_option_id', 'quotes', type_='foreignkey')
    op.drop_constraint('quotes_requested_meal_plan_id_fkey', 'quotes', type_='foreignkey')
    op.drop_column('quotes', 'selected_at')
    op.drop_column('quotes', 'selected_option_id')
    op.drop_column('quotes', 'valid_until')
    op.drop_column('quotes', 'requested_meal_plan_id')
    op.drop_column('quotes', 'contingency_pct')
    op.drop_column('quotes', 'profit_pct')
    op.drop_column('quotes', 'pax_count')
    op.drop_column('activities', 'has_own_section')
    op.drop_column('activities', 'is_mandatory')
    op.drop_column('accommodations', 'blurb')
    op.drop_constraint(
        'accommodation_rates_source_document_id_fkey', 'accommodation_rates',
        type_='foreignkey',
    )
    op.drop_column('accommodation_rates', 'child_max_age')
    op.drop_column('accommodation_rates', 'child_min_age')
    op.drop_column('accommodation_rates', 'source_document_id')
    op.drop_column('accommodation_rates', 'supplier_discount_pct')
    op.drop_column('accommodation_rates', 'rate_kind')
    op.drop_column('accommodation_rates', 'vat_pct')
    op.drop_column('accommodation_rates', 'vat_inclusive')
    op.drop_index(op.f('ix_supplier_document_extractions_status'), table_name='supplier_document_extractions')
    op.drop_index(op.f('ix_supplier_document_extractions_document_id'), table_name='supplier_document_extractions')
    op.drop_table('supplier_document_extractions')
    op.drop_index(op.f('ix_quote_version_options_version_id'), table_name='quote_version_options')
    op.drop_table('quote_version_options')
    op.drop_index(op.f('ix_quote_transport_segments_quote_id'), table_name='quote_transport_segments')
    op.drop_table('quote_transport_segments')
    op.drop_index(op.f('ix_quote_rejected_candidates_quote_id'), table_name='quote_rejected_candidates')
    op.drop_table('quote_rejected_candidates')
    op.drop_index(op.f('ix_quote_options_quote_id'), table_name='quote_options')
    op.drop_table('quote_options')
    op.drop_index(op.f('ix_supplier_documents_status'), table_name='supplier_documents')
    op.drop_index(op.f('ix_supplier_documents_checksum'), table_name='supplier_documents')
    op.drop_index(op.f('ix_supplier_documents_accommodation_id'), table_name='supplier_documents')
    op.drop_table('supplier_documents')
    op.drop_index(op.f('ix_property_images_checksum'), table_name='property_images')
    op.drop_index(op.f('ix_property_images_accommodation_id'), table_name='property_images')
    op.drop_table('property_images')
    op.drop_index(op.f('ix_activity_price_tiers_effective_to'), table_name='activity_price_tiers')
    op.drop_index(op.f('ix_activity_price_tiers_effective_from'), table_name='activity_price_tiers')
    op.drop_index(op.f('ix_activity_price_tiers_activity_id'), table_name='activity_price_tiers')
    op.drop_table('activity_price_tiers')
    op.drop_index(op.f('ix_transfer_rates_vehicle_type'), table_name='transfer_rates')
    op.drop_index(op.f('ix_transfer_rates_effective_to'), table_name='transfer_rates')
    op.drop_index(op.f('ix_transfer_rates_effective_from'), table_name='transfer_rates')
    op.drop_index(op.f('ix_transfer_rates_destination_id'), table_name='transfer_rates')
    op.drop_table('transfer_rates')
    op.drop_index(op.f('ix_destination_transport_modes_mode'), table_name='destination_transport_modes')
    op.drop_index(op.f('ix_destination_transport_modes_effective_to'), table_name='destination_transport_modes')
    op.drop_index(op.f('ix_destination_transport_modes_effective_from'), table_name='destination_transport_modes')
    op.drop_index(op.f('ix_destination_transport_modes_destination_id'), table_name='destination_transport_modes')
    op.drop_table('destination_transport_modes')
    op.drop_index(op.f('ix_destination_images_destination_id'), table_name='destination_images')
    op.drop_index(op.f('ix_destination_images_checksum'), table_name='destination_images')
    op.drop_table('destination_images')
    # ### end Alembic commands ###
