"""stage7_2: client access to their own trip

One row is one client's read-only access to one booking.

Clients are deliberately not ``users``: no password, no registration, no reset.
A users row carries roles and permissions into every guard in the system, and a
client belongs on the other side of that boundary — and somebody who books one
trip every year or two has forgotten a password by the time they need it, so
the login-support cost is real and what it guards is one itinerary.

``token_hash`` is SHA-256 of a 256-bit token, and the plaintext is returned
exactly once at creation. A table of live links is a table of credentials; an
agent who needs to resend issues a new grant, which is also separately
revocable — which is what you want once the first one has been forwarded into a
family group chat. Not bcrypt: a work factor exists to make guessing a
low-entropy secret expensive, there is nothing here to slow down, and the value
has to be looked up by equality.

Scoped to one booking rather than to a client, so a leaked link exposes one
trip. Revocable, with the reason kept. ``last_seen_at``/``view_count`` rather
than an access log: "did they even open the itinerary?" is a real sales
question, and a row per page view would grow without bound and prove nothing,
since a forwarded link is indistinguishable from the client's own browser.

Revision ID: 0ff0bb66eb7a
Revises: 53e05704e2f9
Create Date: 2026-09-04 21:47:52.220187
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0ff0bb66eb7a'
down_revision: Union[str, Sequence[str], None] = '53e05704e2f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_access_grants',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.Column('revoke_reason', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_booking_access_token')
    )
    op.create_index('ix_booking_access_booking', 'booking_access_grants', ['booking_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_booking_access_booking', table_name='booking_access_grants')
    op.drop_table('booking_access_grants')
    # ### end Alembic commands ###
