"""stage2.2 accommodations, room types, meal plans, rates

Revision ID: 16e64eb75e55
Revises: 5e4010dc185e
Create Date: 2026-08-13 19:10:37.253202
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '16e64eb75e55'
down_revision: Union[str, Sequence[str], None] = '5e4010dc185e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_plans',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_plans_code'), 'meal_plans', ['code'], unique=True)
    op.create_table('accommodations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=280), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('star_rating', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('check_in_time', sa.String(length=5), nullable=True),
    sa.Column('check_out_time', sa.String(length=5), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accommodations_name'), 'accommodations', ['name'], unique=False)
    op.create_index(op.f('ix_accommodations_slug'), 'accommodations', ['slug'], unique=True)
    op.create_table('room_types',
    sa.Column('accommodation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('max_occupancy', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accommodation_rates',
    sa.Column('accommodation_id', sa.UUID(), nullable=False),
    sa.Column('room_type_id', sa.UUID(), nullable=False),
    sa.Column('meal_plan_id', sa.UUID(), nullable=False),
    sa.Column('residence_category_id', sa.UUID(), nullable=False),
    sa.Column('season_name', sa.String(length=60), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rate_per_night', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('child_rate', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('single_supplement', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('min_nights', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['residence_category_id'], ['residence_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_type_id', 'meal_plan_id', 'residence_category_id', 'effective_from', name='uq_accommodation_rate_period')
    )
    op.create_index(op.f('ix_accommodation_rates_accommodation_id'), 'accommodation_rates', ['accommodation_id'], unique=False)
    op.create_index(op.f('ix_accommodation_rates_effective_from'), 'accommodation_rates', ['effective_from'], unique=False)
    op.create_index(op.f('ix_accommodation_rates_effective_to'), 'accommodation_rates', ['effective_to'], unique=False)
    op.create_index(op.f('ix_accommodation_rates_room_type_id'), 'accommodation_rates', ['room_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accommodation_rates_room_type_id'), table_name='accommodation_rates')
    op.drop_index(op.f('ix_accommodation_rates_effective_to'), table_name='accommodation_rates')
    op.drop_index(op.f('ix_accommodation_rates_effective_from'), table_name='accommodation_rates')
    op.drop_index(op.f('ix_accommodation_rates_accommodation_id'), table_name='accommodation_rates')
    op.drop_table('accommodation_rates')
    op.drop_table('room_types')
    op.drop_index(op.f('ix_accommodations_slug'), table_name='accommodations')
    op.drop_index(op.f('ix_accommodations_name'), table_name='accommodations')
    op.drop_table('accommodations')
    op.drop_index(op.f('ix_meal_plans_code'), table_name='meal_plans')
    op.drop_table('meal_plans')
    # ### end Alembic commands ###
