"""stage2.3 park and conservation fees

Revision ID: 1e580ba3e64e
Revises: 16e64eb75e55
Create Date: 2026-08-14 08:23:43.851968
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e580ba3e64e'
down_revision: Union[str, Sequence[str], None] = '16e64eb75e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('park_fees',
    sa.Column('destination_id', sa.UUID(), nullable=False),
    sa.Column('fee_type', sa.String(length=30), nullable=False),
    sa.Column('residence_category_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('adult', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('child', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('infant', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('child_min_age', sa.Integer(), nullable=False),
    sa.Column('child_max_age', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['residence_category_id'], ['residence_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination_id', 'fee_type', 'residence_category_id', 'effective_from', name='uq_park_fee_period')
    )
    op.create_index(op.f('ix_park_fees_destination_id'), 'park_fees', ['destination_id'], unique=False)
    op.create_index(op.f('ix_park_fees_effective_from'), 'park_fees', ['effective_from'], unique=False)
    op.create_index(op.f('ix_park_fees_effective_to'), 'park_fees', ['effective_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_park_fees_effective_to'), table_name='park_fees')
    op.drop_index(op.f('ix_park_fees_effective_from'), table_name='park_fees')
    op.drop_index(op.f('ix_park_fees_destination_id'), table_name='park_fees')
    op.drop_table('park_fees')
    # ### end Alembic commands ###
