"""stage3_1b occupancy rates and supplements

Supplier rate sheets price a room by how many people sleep in it (26 of the 32
machine-readable 2026/27 sheets do), and the old uniqueness key had no room for
that: Single/Double/Triple for one room+meal+season differ only by occupancy and
collided. Adds the column, widens the key, and adds the supplement table that
festive loadings and compulsory gala dinners need.

NOTE ON DOWNGRADE: restoring the narrow unique key will FAIL if any property has
occupancy-differing rates stored, because those rows become duplicates. That is
intentional — the alternative is deleting real rates silently. Remove the extra
occupancy rows deliberately before downgrading.

Revision ID: 316e59973b79
Revises: 03e1ff30d1ad
Create Date: 2026-08-24 22:08:02.616246
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '316e59973b79'
down_revision: Union[str, Sequence[str], None] = '03e1ff30d1ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accommodation_supplements',
    sa.Column('accommodation_id', sa.UUID(), nullable=False),
    sa.Column('room_type_id', sa.UUID(), nullable=True),
    sa.Column('meal_plan_id', sa.UUID(), nullable=True),
    sa.Column('residence_category_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('basis', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('vat_inclusive', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('vat_pct', sa.Numeric(precision=5, scale=2), server_default=sa.text('16'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_document_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accommodation_id'], ['accommodations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_plan_id'], ['meal_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['residence_category_id'], ['residence_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_type_id'], ['room_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['supplier_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accommodation_id', 'label', 'effective_from', name='uq_accommodation_supplement_period')
    )
    op.create_index(op.f('ix_accommodation_supplements_accommodation_id'), 'accommodation_supplements', ['accommodation_id'], unique=False)
    op.create_index(op.f('ix_accommodation_supplements_effective_from'), 'accommodation_supplements', ['effective_from'], unique=False)
    op.create_index(op.f('ix_accommodation_supplements_effective_to'), 'accommodation_supplements', ['effective_to'], unique=False)
    # server_default 2: the column is NOT NULL on a populated table, and the
    # existing rows are all per-room prices for two sharing.
    op.add_column('accommodation_rates', sa.Column('occupancy', sa.Integer(), server_default=sa.text('2'), nullable=False))
    op.drop_constraint(op.f('uq_accommodation_rate_period'), 'accommodation_rates', type_='unique')
    op.create_unique_constraint('uq_accommodation_rate_period', 'accommodation_rates', ['room_type_id', 'meal_plan_id', 'residence_category_id', 'occupancy', 'effective_from'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_accommodation_rate_period', 'accommodation_rates', type_='unique')
    op.create_unique_constraint(op.f('uq_accommodation_rate_period'), 'accommodation_rates', ['room_type_id', 'meal_plan_id', 'residence_category_id', 'effective_from'], postgresql_nulls_not_distinct=False)
    op.drop_column('accommodation_rates', 'occupancy')
    op.drop_index(op.f('ix_accommodation_supplements_effective_to'), table_name='accommodation_supplements')
    op.drop_index(op.f('ix_accommodation_supplements_effective_from'), table_name='accommodation_supplements')
    op.drop_index(op.f('ix_accommodation_supplements_accommodation_id'), table_name='accommodation_supplements')
    op.drop_table('accommodation_supplements')
    # ### end Alembic commands ###
