"""stage5_3: the contact log

One row is one call, email, message, meeting or internal note, against
whichever of four things the conversation was about (a lead, a client, a quote,
a booking). It is a log and not a mailbox: nothing sends anything, and
``external_ref`` is where a provider message id lands when there is one.

``occurred_at`` is kept apart from the mixin's ``created_at`` on purpose. Almost
everything here is written up after the fact, and measuring a response time
against when the notes were typed would flatter whoever types them promptly.

The two columns on ``leads`` are denormalised from this table and maintained by
the comms service: the morning list runs over every open lead, and a subquery
per lead for "when did we last speak to them" is what makes a list slow enough
to stop being opened. Safe because they are derivable —
``CommsService.recompute`` rebuilds both, and a test proves it agrees.

They also fix something §5.2 had wrong for want of this table. Staleness was
measured by stage movement, which is not the same question: an agent can call a
client weekly without moving a stage, and a lead can be dragged across three
stages while nobody has picked up the phone.

Revision ID: 53e05704e2f9
Revises: 65fd3c1a37bf
Create Date: 2026-09-04 21:04:53.504573
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '53e05704e2f9'
down_revision: Union[str, Sequence[str], None] = '65fd3c1a37bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communications',
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=40), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject_line', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('reached', sa.Boolean(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('external_ref', sa.String(length=200), nullable=True),
    sa.Column('logged_by', sa.UUID(), nullable=True),
    sa.Column('amended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amended_by', sa.UUID(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_by', sa.UUID(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("direction in ('inbound', 'outbound', 'internal')", name='ck_communication_direction'),
    sa.CheckConstraint("subject in ('lead', 'client', 'quote', 'booking')", name='ck_communication_subject'),
    sa.CheckConstraint('duration_minutes is null or (duration_minutes > 0 and reached is not false)', name='ck_communication_duration'),
    sa.ForeignKeyConstraint(['amended_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['logged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_communication_subject', 'communications', ['subject', 'subject_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_communications_occurred_at'), 'communications', ['occurred_at'], unique=False)
    op.add_column('leads', sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('leads', sa.Column('last_inbound_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'last_inbound_at')
    op.drop_column('leads', 'last_contact_at')
    op.drop_index(op.f('ix_communications_occurred_at'), table_name='communications')
    op.drop_index('ix_communication_subject', table_name='communications')
    op.drop_table('communications')
    # ### end Alembic commands ###
