"""stage5_2: leads, the pipeline, and where a quote came from

Three tables and a column.

``lead_stages`` is the sales process as **rows**: ordered, renameable, with
flags saying which stage means won and which mean lost. Heissal has not told us
their stages, and a CHECK constraint listing mine would need a migration the
first time somebody wants "site inspection" between quoted and negotiating.
Reports ask "which stage means won" rather than comparing a name, so renaming
one cannot break a figure.

``leads`` holds the enquiry as it actually arrives — a name, a phone number,
"somewhere on the coast in August, maybe six of us" — so ``client_id`` is
nullable and the wishes are loose text. ``next_action_on`` is the field that
decides whether a CRM is used: a lead with nothing scheduled appears on no
list and dies quietly.

``lead_stage_events`` is what makes it a pipeline rather than a status column.
"Eleven at quoted" is a number; "eleven at quoted, median nineteen days" is a
morning's work, and only the history can say the second.

``quotes.lead_id`` is what lets §5.1's funnel be sliced by source: which
channels convert, not merely which produce enquiries.


Revision ID: 6098a8bc6428
Revises: f11242360320
Create Date: 2026-09-04 19:25:02.076618
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6098a8bc6428'
down_revision: Union[str, Sequence[str], None] = 'f11242360320'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_stages',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_won', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_lost', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', name='uq_lead_stage_key')
    )
    op.create_index('ix_lead_stage_order', 'lead_stages', ['sort_order'], unique=False)
    op.create_table('leads',
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('source_detail', sa.String(length=160), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('contact_name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('stage_id', sa.UUID(), nullable=False),
    sa.Column('stage_since', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('destination_interest', sa.String(length=200), nullable=True),
    sa.Column('travel_from', sa.Date(), nullable=True),
    sa.Column('travel_to', sa.Date(), nullable=True),
    sa.Column('pax_estimate', sa.Integer(), nullable=True),
    sa.Column('budget_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('budget_currency', sa.String(length=3), nullable=True),
    sa.Column('next_action_on', sa.Date(), nullable=True),
    sa.Column('next_action_note', sa.Text(), nullable=True),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_id'], ['lead_stages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lead_next_action', 'leads', ['next_action_on'], unique=False)
    op.create_index('ix_lead_stage_owner', 'leads', ['stage_id', 'owner_id'], unique=False)
    op.create_index(op.f('ix_leads_contact_email'), 'leads', ['contact_email'], unique=False)
    op.create_table('lead_stage_events',
    sa.Column('lead_id', sa.UUID(), nullable=False),
    sa.Column('from_stage_id', sa.UUID(), nullable=True),
    sa.Column('to_stage_id', sa.UUID(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('by', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['from_stage_id'], ['lead_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_stage_id'], ['lead_stages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lead_stage_event_lead', 'lead_stage_events', ['lead_id', 'at'], unique=False)
    op.add_column('quotes', sa.Column('lead_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'quotes', 'leads', ['lead_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_column('quotes', 'lead_id')
    op.drop_index('ix_lead_stage_event_lead', table_name='lead_stage_events')
    op.drop_table('lead_stage_events')
    op.drop_index(op.f('ix_leads_contact_email'), table_name='leads')
    op.drop_index('ix_lead_stage_owner', table_name='leads')
    op.drop_index('ix_lead_next_action', table_name='leads')
    op.drop_table('leads')
    op.drop_index('ix_lead_stage_order', table_name='lead_stages')
    op.drop_table('lead_stages')
    # ### end Alembic commands ###
