"""stage7_1: where an accepted quote leads

Until now it led nowhere. A deal could be won in the system (§5.1) and
operations picked it up in a spreadsheet.

``bookings`` points at the **version**, not the quote: the version holds the
immutable snapshot the client accepted, and a booking whose total could move
because somebody re-priced the quote is not a booking. The dates, the headcount
and the figure are copied onto it, because an operations screen showing
different dates after somebody edited the quote is worse than useless.

``booking_instalments`` is the schedule as invoice lines rather than a deposit
percentage. "50% deposit" is policy; "KES 223,750 due on 4 September" is what a
client pays and what a statement is reconciled against — and dated rows are what
make the terms frozen when the policy changes next month.

``payments`` is money that arrived, recorded and never inferred, with the
reference that finds it in somebody else's system. No integration yet: M-Pesa
will land behind these same rows, and a booking that trusted a callback over a
reconciled statement is a booking nobody can audit.

No cancellation charge is computed anywhere. That ladder is commercial policy
nobody has given us.


Revision ID: 65fd3c1a37bf
Revises: 6098a8bc6428
Create Date: 2026-09-04 19:52:55.287962
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '65fd3c1a37bf'
down_revision: Union[str, Sequence[str], None] = '6098a8bc6428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_counters',
    sa.Column('year', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('bookings',
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('quote_id', sa.UUID(), nullable=False),
    sa.Column('quote_version_id', sa.UUID(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('pax_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('provisional', 'confirmed', 'cancelled', 'completed')", name='ck_booking_status'),
    sa.CheckConstraint('departure_date > arrival_date', name='ck_booking_dates'),
    sa.CheckConstraint('total_amount >= 0', name='ck_booking_total_positive'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['option_id'], ['quote_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_booking_quote', 'bookings', ['quote_id'], unique=False)
    op.create_index('ix_booking_status_dates', 'bookings', ['status', 'arrival_date'], unique=False)
    op.create_index(op.f('ix_bookings_reference'), 'bookings', ['reference'], unique=True)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('booking_instalments',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=60), nullable=False),
    sa.Column('due_on', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_instalment_amount_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_instalment_due', 'booking_instalments', ['due_on'], unique=False)
    op.create_table('payments',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('instalment_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payment_amount_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instalment_id'], ['booking_instalments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_booking', 'payments', ['booking_id', 'paid_on'], unique=False)
    op.create_index(op.f('ix_payments_reference'), 'payments', ['reference'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_reference'), table_name='payments')
    op.drop_index('ix_payment_booking', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_instalment_due', table_name='booking_instalments')
    op.drop_table('booking_instalments')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_reference'), table_name='bookings')
    op.drop_index('ix_booking_status_dates', table_name='bookings')
    op.drop_index('ix_booking_quote', table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('booking_counters')
    # ### end Alembic commands ###
