"""stage4_4: proposal copy, and the review it has to pass

One table, three states: drafted, approved, rejected. Only an approved row may
reach a client document, and approval is its own permission — the same split as
issuing a quotation, and for the same reason: composing something and putting it
in front of a client are different levels of trust.

``subject`` plus ``subject_id`` rather than two nullable foreign keys, because
the review pipeline for a property and for a destination is identical and a
second copy of it is a second place for the gate to be got wrong. The trade is
that deletion is the service's job rather than the database's.

Nothing is overwritten: a rejected draft is the record of what was nearly sent,
and a superseded one is what an already-issued proposal actually said.


Revision ID: 8b87b4cdb902
Revises: 9ed0fe038498
Create Date: 2026-09-04 18:45:06.781296
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8b87b4cdb902'
down_revision: Union[str, Sequence[str], None] = '9ed0fe038498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('narratives',
    sa.Column('subject', sa.String(length=20), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('brief', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('draft', 'approved', 'rejected')", name='ck_narrative_status'),
    sa.CheckConstraint("subject in ('accommodation', 'destination')", name='ck_narrative_subject'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_narrative_subject_status', 'narratives', ['subject', 'subject_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_narrative_subject_status', table_name='narratives')
    op.drop_table('narratives')
    # ### end Alembic commands ###
