"""stage8_3: the supplier side of a booking

§7.1 built the client side completely: what they owe, when, and what has
arrived. There has never been a counterpart. Every quote is costed from
supplier rates and every version snapshot carries a ``supplier_paid_total``,
and nothing in this system had ever told a hotel that a group was coming,
recorded that they said yes, or noticed that they invoiced more than we
budgeted.

Two failures follow. **The room was never actually booked** — a trip departs,
the departure board is green on vehicle, driver and seats, and the lodge has no
reservation, because §8.1 asked who was driving and never asked whether anybody
had rung. So an unconfirmed supplier is now a column on that board, on a
threshold the business sets: a Diani hotel in May will take a booking on the
Thursday and a Mara camp in August wanted it in February.

And **the margin quietly went** — a package costed at 180,000 and invoiced at
195,000 has eaten a fifth of the profit, and until ``expected_amount`` and
``invoiced_amount`` sat on one row nothing would ever have compared them. That
is §8.2's argument about the fuel model, in a different currency.

``expected_amount`` is typed off the contract, not derived: the snapshot holds
one figure for a whole option across every supplier on it, so a per-hotel split
would be a guess dressed as a fact. ``invoiced_amount`` and ``settled_amount``
are NULL rather than zero until they happen, which is a different thing.
Nothing is ever summed across currencies — a lodge billing in dollars beside a
transfer company billing in shillings is the normal case here.

The row is not tied to an option or a leg: a trip's suppliers are a hotel, a
transfer company and a park gate, and only one of those is on a leg. It names
its own ``service`` instead.

Revision ID: 90dd20bbab6a
Revises: bff02a79fd8c
Create Date: 2026-09-05 15:07:01.738330
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '90dd20bbab6a'
down_revision: Union[str, Sequence[str], None] = 'bff02a79fd8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier_bookings',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('service', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('their_reference', sa.String(length=120), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=True),
    sa.Column('check_out', sa.Date(), nullable=True),
    sa.Column('confirm_by', sa.Date(), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('invoiced_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('settled_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('requested_on', sa.Date(), nullable=True),
    sa.Column('confirmed_on', sa.Date(), nullable=True),
    sa.Column('settled_on', sa.Date(), nullable=True),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('to_request', 'requested', 'confirmed', 'cancelled')", name='ck_supplier_booking_status'),
    sa.CheckConstraint('check_out is null or check_in is null or check_out >= check_in', name='ck_supplier_booking_dates'),
    sa.CheckConstraint('expected_amount >= 0', name='ck_supplier_booking_expected'),
    sa.CheckConstraint('invoiced_amount is null or invoiced_amount >= 0', name='ck_supplier_booking_invoiced'),
    sa.CheckConstraint('settled_amount is null or settled_amount >= 0', name='ck_supplier_booking_settled'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_supplier_booking_booking', 'supplier_bookings', ['booking_id'], unique=False)
    op.create_index('ix_supplier_booking_supplier', 'supplier_bookings', ['supplier_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_supplier_booking_supplier', table_name='supplier_bookings')
    op.drop_index('ix_supplier_booking_booking', table_name='supplier_bookings')
    op.drop_table('supplier_bookings')
    # ### end Alembic commands ###
