"""stage2.4 activities and activity rates

Revision ID: a6379421aff0
Revises: 1e580ba3e64e
Create Date: 2026-08-16 09:10:37.057258
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a6379421aff0'
down_revision: Union[str, Sequence[str], None] = '1e580ba3e64e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('destination_id', sa.UUID(), nullable=True),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_id'], ['destinations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_name'), 'activities', ['name'], unique=False)
    op.create_index(op.f('ix_activities_slug'), 'activities', ['slug'], unique=True)
    op.create_table('activity_rates',
    sa.Column('activity_id', sa.UUID(), nullable=False),
    sa.Column('residence_category_id', sa.UUID(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('adult_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('child_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['residence_category_id'], ['residence_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id', 'residence_category_id', 'effective_from', name='uq_activity_rate_period')
    )
    op.create_index(op.f('ix_activity_rates_activity_id'), 'activity_rates', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_rates_effective_from'), 'activity_rates', ['effective_from'], unique=False)
    op.create_index(op.f('ix_activity_rates_effective_to'), 'activity_rates', ['effective_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_rates_effective_to'), table_name='activity_rates')
    op.drop_index(op.f('ix_activity_rates_effective_from'), table_name='activity_rates')
    op.drop_index(op.f('ix_activity_rates_activity_id'), table_name='activity_rates')
    op.drop_table('activity_rates')
    op.drop_index(op.f('ix_activities_slug'), table_name='activities')
    op.drop_index(op.f('ix_activities_name'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
