"""stage8_2: what the vehicle actually did

Every quote this platform has produced charges a drive from a distance and a
``fuel_consumption_kmpl`` somebody typed onto a ``vehicles`` row once (§2.5).
§8.1 committed a real vehicle to a real trip. Nothing has ever recorded what
that vehicle **did**, so the figure at the centre of every transport line has
never been checked against a fuel receipt.

That is a quieter failure than the missing columns earlier stages found: a
vehicle priced at 8.5 km/L that really manages 6.9 under-costs every safari by
a fifth, for as long as nobody measures.

``trip_logs`` is one odometer pair per **vehicle assignment**, not per booking:
a group in two Land Cruisers is two odometers and two sets of receipts, and
pooling them would lose exactly the comparison worth making. ``odometer_in_km``
is nullable because a log is opened when the vehicle leaves and closed when it
returns, and the days between are when somebody wants to know where it is. The
CHECK refuses a closing reading below the opening one — an odometer does not
run backwards, so it is a typed digit, and a negative distance poisons every
average derived from it.

``fuel_fills`` holds litres **and** money, both off the receipt and neither
derived from the other: a litre price computed by division loses the partial
fill, the price that changed mid-trip, and the pump out at Voi charging a
premium.

Nothing here changes ``fuel_consumption_kmpl``. The audit reports that a
vehicle's model is out; it does not move a live pricing input, because that
would re-price work in flight.

Revision ID: bff02a79fd8c
Revises: bf98e7401b33
Create Date: 2026-09-05 08:13:56.940210
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bff02a79fd8c'
down_revision: Union[str, Sequence[str], None] = 'bf98e7401b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_logs',
    sa.Column('assignment_id', sa.UUID(), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('odometer_out_km', sa.Numeric(precision=12, scale=1), nullable=False),
    sa.Column('odometer_in_km', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('started_on', sa.Date(), nullable=False),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('odometer_in_km is null or odometer_in_km >= odometer_out_km', name='ck_trip_log_odometer'),
    sa.CheckConstraint('odometer_out_km >= 0', name='ck_trip_log_out_positive'),
    sa.ForeignKeyConstraint(['assignment_id'], ['trip_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['driver_id'], ['crew.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id', name='uq_trip_log_assignment')
    )
    op.create_index('ix_trip_log_vehicle', 'trip_logs', ['vehicle_id', 'started_on'], unique=False)
    op.create_table('fuel_fills',
    sa.Column('trip_log_id', sa.UUID(), nullable=False),
    sa.Column('litres', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('bought_on', sa.Date(), nullable=False),
    sa.Column('station', sa.String(length=160), nullable=True),
    sa.Column('receipt_ref', sa.String(length=80), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_fuel_fill_amount'),
    sa.CheckConstraint('litres > 0', name='ck_fuel_fill_litres'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trip_log_id'], ['trip_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fuel_fill_log', 'fuel_fills', ['trip_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fuel_fill_log', table_name='fuel_fills')
    op.drop_table('fuel_fills')
    op.drop_index('ix_trip_log_vehicle', table_name='trip_logs')
    op.drop_table('trip_logs')
    # ### end Alembic commands ###
