"""stage2.5 vehicles and fuel prices

Revision ID: ef29107c8ca1
Revises: a6379421aff0
Create Date: 2026-08-16 09:19:31.343798
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ef29107c8ca1'
down_revision: Union[str, Sequence[str], None] = 'a6379421aff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuel_prices',
    sa.Column('fuel_type', sa.String(length=20), nullable=False),
    sa.Column('price_per_litre', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fuel_type', 'effective_from', name='uq_fuel_price_period')
    )
    op.create_index(op.f('ix_fuel_prices_effective_from'), 'fuel_prices', ['effective_from'], unique=False)
    op.create_index(op.f('ix_fuel_prices_fuel_type'), 'fuel_prices', ['fuel_type'], unique=False)
    op.create_table('vehicles',
    sa.Column('slug', sa.String(length=280), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('vehicle_type', sa.String(length=60), nullable=False),
    sa.Column('registration', sa.String(length=30), nullable=True),
    sa.Column('passenger_capacity', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(length=20), nullable=False),
    sa.Column('fuel_consumption_kmpl', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('cost_per_km', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('daily_operating_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('driver_cost_per_day', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_name'), 'vehicles', ['name'], unique=False)
    op.create_index(op.f('ix_vehicles_slug'), 'vehicles', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_slug'), table_name='vehicles')
    op.drop_index(op.f('ix_vehicles_name'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_fuel_prices_fuel_type'), table_name='fuel_prices')
    op.drop_index(op.f('ix_fuel_prices_effective_from'), table_name='fuel_prices')
    op.drop_table('fuel_prices')
    # ### end Alembic commands ###
