"""stage5_1: what happened to a quote

``quotes.status`` has listed ``accepted`` and ``declined`` since Stage 2 and
nothing could set them, so no quote in the system had ever been won or lost and
the CRM's first question had no data at all.

Three columns, and the third is the one the business will read: when the
decision was taken, who on our side recorded it, and WHY a loss was a loss. A
funnel that counts losses without reasons says you are losing and nothing about
what to change.

No ``expired`` column: expiry is derived from ``valid_until`` at read time (see
``app.modules.quotes.outcomes``), because a quote is expired when somebody looks
at it and not when a nightly job last ran.


Revision ID: f11242360320
Revises: 8b87b4cdb902
Create Date: 2026-09-04 19:07:15.804860
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f11242360320'
down_revision: Union[str, Sequence[str], None] = '8b87b4cdb902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotes', sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quotes', sa.Column('decided_by', sa.UUID(), nullable=True))
    op.add_column('quotes', sa.Column('decision_note', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'quotes', 'users', ['decided_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotes', type_='foreignkey')
    op.drop_column('quotes', 'decision_note')
    op.drop_column('quotes', 'decided_by')
    op.drop_column('quotes', 'decided_at')
    # ### end Alembic commands ###
